// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQQS5xwkBW7O4KZHInX930CxtL2FJIsqU',
    appId: '1:77383749731:web:4e9138f5f2d6c2304a6856',
    messagingSenderId: '77383749731',
    projectId: 'greenovate-5641c',
    authDomain: 'greenovate-5641c.firebaseapp.com',
    storageBucket: 'greenovate-5641c.firebasestorage.app',
    measurementId: 'G-TS6WVPVE5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpeFPOvCtFQ15YdrJDk2lVehJU6i1gYLU',
    appId: '1:77383749731:android:035174ef871f19c24a6856',
    messagingSenderId: '77383749731',
    projectId: 'greenovate-5641c',
    storageBucket: 'greenovate-5641c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVYwbFEByDtX9yVja3n7MCPeSHrqrK4c',
    appId: '1:77383749731:ios:82e0eed3566ebdb04a6856',
    messagingSenderId: '77383749731',
    projectId: 'greenovate-5641c',
    storageBucket: 'greenovate-5641c.firebasestorage.app',
    iosBundleId: 'com.example.greenovate',
  );
}
